use Mix.Config
config :bookmarker, 
    osx_bookmarks_file: "~/Library/Application\ Support/Google/Chrome/Default/Bookmarks",
    linux_bookmarks_file: "~/.config/google-chrome/Default/Bookmarks",
    windows_bookmarks_file: "\\AppData\\Local\\Google\\Chrome\\User\ Data\\Default",
    default_title: "Google Chrome Bookmarks",
    default_description: "Generated by [Bookmarker](https://github.com/lubien/bookmarker)"
