use Mix.Config
config :bookmarker, bookmarks_file: "~/.config/google-chrome/Default/Bookmarks",
                    default_title: "Google Chrome Bookmarks",
                    default_description: "Generated by [Bookmarker](https://github.com/lubien/bookmarker)"
